TestSeleniumReport/Models/Environments.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestSeleniumReport.Models
{
    public class Environments
    {
        [Key]
        public int EnvironmentId { get; set; }

        [Required(ErrorMessage = "Environment Name is required."), Column("EnvironmentName", TypeName = "varchar(100)")]
        public string EnvironmentName { get; set; }

        public int ApplicationId { get; set; }

        [Required(ErrorMessage = "Baseurl is required."), Column("Baseurl", TypeName = "varchar(1000)")]
        public string Baseurl { get; set; }

        [Required(ErrorMessage = "BasePath is required."), Column("BasePath", TypeName = "varchar(1000)")]
        public string BasePath { get; set; }

        [Required(ErrorMessage = "DriverPath  is required."), Column("DriverPath", TypeName = "varchar(1000)")]
        public string DriverPath { get; set; }

        public int BroswerId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }

        [NotMapped]
        public string ApplicationName { get; set; }

        [NotMapped]
        public string BrowserName { get; set; }
        public string? Description { get; set; }
    }
}

TestSeleniumReport/Controllers/EnvironmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SeleniumTestReport.Helper;
using TestSeleniumReport.DTO_s;

namespace TestSeleniumReport.Controllers
{
    public class EnvironmentController : Controller
    {
        private readonly DBHelper _helper;

        public EnvironmentController(DBHelper helper)
        {
            _helper = helper;
        }

        public IActionResult Index()
        {
            try
            {
                var EnvironmentListJson = _helper.GetEnvironments();
                List<Models.Environments> _environmentList = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Models.Environments>>(EnvironmentListJson);
                return View(_environmentList);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult Add()
        {
            var ApplicationListJson = _helper.GetApplications();
            List<Models.Applications> _applicationList = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Models.Applications>>(ApplicationListJson);
            var BrowserListJson = _helper.GetBrowsers();
            List<Models.Browsers> _BrowsersList = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Models.Browsers>>(BrowserListJson);
            ViewBag.Applications = new SelectList(_applicationList, "ApplicationId", "ApplicationName");
            ViewBag.Browsers = new SelectList(_BrowsersList, "BrowserId", "BrowserName");
            ViewBag.AddOrEditPage = "Add";
            Models.Environments environments = new Models.Environments();
            return View("AddEditEnvironment", environments);
        }

        [HttpPost]
        public IActionResult Add(Models.Environments model, string action)
        {
            Dto_Response _response = new Dto_Response();
            if (model != null)
            {
                string result = _helper.AddUpdateEnvironmentJson(model);
                _response = Newtonsoft.Json.JsonConvert.DeserializeObject<Dto_Response>(result);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            Models.Environments environments = _helper.GetEnvironmentById(id);
            var ApplicationListJson = _helper.GetApplications();
            List<Models.Applications> _applicationList = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Models.Applications>>(ApplicationListJson);
            var Browserss = _helper.GetBrowsers();
            List<Models.Browsers> _Browserss = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Models.Browsers>>(Browserss);

            // Prepare data for dropdowns
            ViewBag.Applications = new SelectList(_applicationList, "ApplicationId", "ApplicationName");
            ViewBag.Browsers = new SelectList(_Browserss, "BrowserId", "BrowserName");
            ViewBag.AddOrEditPage = "Add";
            return View("AddEditEnvironment", environments);
        }
    }
}

TestSeleniumReport/Views/Environment/AddEditEnvironment.cshtml
@model TestSeleniumReport.Models.Environments

@{
    Layout = "_Layout";
    var addOrEditPage = ViewBag.AddOrEditPage.ToString();
}



<form asp-action="@(addOrEditPage == "Add" ? "Add" : "Edit" )" method="post">
    <input asp-for="EnvironmentId" hidden />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <table>
        <tr>
            <td><label class="control-label">Environment Name</label></td>
            <td> @Html.TextBoxFor(model => model.EnvironmentName, new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td> <label class="control-label">Application Name</label></td>
            <td> @Html.DropDownListFor(model => model.ApplicationId, (SelectList)ViewBag.Applications, "Select Application", new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td> <label class="control-label">Browser Name</label></td>
            <td> @Html.DropDownListFor(model => model.BroswerId, (SelectList)ViewBag.Browsers, "Select Browser", new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td><label class="control-label">Baseurl</label></td>
            <td> @Html.TextBoxFor(model => model.Baseurl, new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td><label class="control-label">BasePath</label></td>
            <td> @Html.TextBoxFor(model => model.BasePath, new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td><label class="control-label">DriverPath</label></td>
            <td> @Html.TextBoxFor(model => model.DriverPath, new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit" class="btn btn-primary">Save</button>
                <a type="button" class="btn btn-secondary" asp-action="Index">Cancel</a>
            </td>
        </tr>
    </table>
</form>
@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />;
    }

TestSeleniumReport/Views/Environment/Index.cshtml
@model List<Environments>

<!DOCTYPE html>
<html>
<head>
    <title>Application List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="mt-4">
        <h2>Environment List</h2>

        <button type="button" class="btn btn-primary float-end" onclick="AddEditEnviroment()">
            Add Environment
        </button>

        <!-- Table to display the list of items -->
        <table class="table mt-3">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Application Name</th>
                    <th>Browser Name</th>
                    <th>Base Url</th>
                    <th>Base Path</th>
                    <th>Driver Path</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var environment in Model)
                    {
                        <tr>
                            <td>@environment.EnvironmentName</td>
                            <td>@environment.ApplicationName</td>
                            <td >@environment.BrowserName</td>
                            <td style="max-width: 150px; overflow: hidden; text-overflow: ellipsis;">@environment.Baseurl</td>
                            <td style="max-width: 150px; overflow: hidden; text-overflow: ellipsis;">@environment.BasePath</td>
                            <td style="max-width: 150px; overflow: hidden; text-overflow: ellipsis;">@environment.DriverPath</td>
                            <td>
                                <a class="bg-white border-0" onclick="EditEnvironment(@environment.EnvironmentId)">
                                    <em class="fas fa-edit mx-2 text-success"></em>
                                </a>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
 
</body>
</html>

<script>
    function AddEditEnviroment() {
        window.location.href = '@Url.Action("Add", "Environment")';
    }
    function EditEnvironment(id) {
        var url = '@Url.Action("Edit", "Environment")';
        window.location.href = url + '?id=' + id;
    }

</script>